//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ouranos.RedArmory.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ouranos.RedArmory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   dd/MM/yyyy HH:mm:ss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Format_BackupDate {
            get {
                return ResourceManager.GetString("Format_BackupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to {0} service に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Format_FailedDoService {
            get {
                return ResourceManager.GetString("Format_FailedDoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start of {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Format_StartService {
            get {
                return ResourceManager.GetString("Format_StartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop of {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Format_StopService {
            get {
                return ResourceManager.GetString("Format_StopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Succeed to {0} service に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Format_SucceedDoService {
            get {
                return ResourceManager.GetString("Format_SucceedDoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Lang_English {
            get {
                return ResourceManager.GetString("Lang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Lang_Japanese {
            get {
                return ResourceManager.GetString("Lang_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup is cancelled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_BackupCancel {
            get {
                return ResourceManager.GetString("Msg_BackupCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup is complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_BackupComplete {
            get {
                return ResourceManager.GetString("Msg_BackupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_BackupFailed {
            get {
                return ResourceManager.GetString("Msg_BackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup is skipped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_BackupSkip {
            get {
                return ResourceManager.GetString("Msg_BackupSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitnami Redmine Stack is not present. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_BitnamiRedmineStackIsNotPresent {
            get {
                return ResourceManager.GetString("Msg_BitnamiRedmineStackIsNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete the selected history item? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_DeleteHistory {
            get {
                return ResourceManager.GetString("Msg_DeleteHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The output directory is not empty. Do you want to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_DirectoryIsNotEmpty {
            get {
                return ResourceManager.GetString("Msg_DirectoryIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore is cancelled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_RestoreCancel {
            get {
                return ResourceManager.GetString("Msg_RestoreCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore is complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_RestoreComplete {
            get {
                return ResourceManager.GetString("Msg_RestoreComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_RestoreFailed {
            get {
                return ResourceManager.GetString("Msg_RestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore is skipped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_RestoreSkip {
            get {
                return ResourceManager.GetString("Msg_RestoreSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create backup task to Task Scheduler に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_AddTask {
            get {
                return ResourceManager.GetString("Tooltip_AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create task from this setting and add to task scheduler に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_CreateTaskSchedule {
            get {
                return ResourceManager.GetString("Tooltip_CreateTaskSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_Down {
            get {
                return ResourceManager.GetString("Tooltip_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %LONGDATE% : yyyyMMdd hhmmss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_FolderNameLongDate {
            get {
                return ResourceManager.GetString("Tooltip_FolderNameLongDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %SHORTDATE% : yyyyMMdd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_FolderNameShortDate {
            get {
                return ResourceManager.GetString("Tooltip_FolderNameShortDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %VERSION% : Version of Redmine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_FolderNameVersion {
            get {
                return ResourceManager.GetString("Tooltip_FolderNameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the changes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_Save {
            get {
                return ResourceManager.GetString("Tooltip_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select where you want to save your backup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_SelectBackupFolder {
            get {
                return ResourceManager.GetString("Tooltip_SelectBackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder you want to restore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_SelectRestoreFolder {
            get {
                return ResourceManager.GetString("Tooltip_SelectRestoreFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Backup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_StartBackup {
            get {
                return ResourceManager.GetString("Tooltip_StartBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Restore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_StartRestore {
            get {
                return ResourceManager.GetString("Tooltip_StartRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_Up {
            get {
                return ResourceManager.GetString("Tooltip_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About this application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_AboutThisApplication {
            get {
                return ResourceManager.GetString("Word_AboutThisApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Acknowledgements に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Acknowledgements {
            get {
                return ResourceManager.GetString("Word_Acknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Active {
            get {
                return ResourceManager.GetString("Word_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Activities (time tracking) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Activities_TimeTracking {
            get {
                return ResourceManager.GetString("Word_Activities_TimeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add new task に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_AddTask {
            get {
                return ResourceManager.GetString("Word_AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   April に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_April {
            get {
                return ResourceManager.GetString("Word_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attached Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_AttachedFile {
            get {
                return ResourceManager.GetString("Word_AttachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   August に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_August {
            get {
                return ResourceManager.GetString("Word_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Author {
            get {
                return ResourceManager.GetString("Word_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Free space (MB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_AvailableSpace {
            get {
                return ResourceManager.GetString("Word_AvailableSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create task schedule に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_CreateTaskSchedule {
            get {
                return ResourceManager.GetString("Word_CreateTaskSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Database {
            get {
                return ResourceManager.GetString("Word_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Days に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Days {
            get {
                return ResourceManager.GetString("Word_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   December に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_December {
            get {
                return ResourceManager.GetString("Word_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_DefaultValue {
            get {
                return ResourceManager.GetString("Word_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Description {
            get {
                return ResourceManager.GetString("Word_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Destination {
            get {
                return ResourceManager.GetString("Word_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Document categories に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_DocumentCategories {
            get {
                return ResourceManager.GetString("Word_DocumentCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enumeration Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_EnumerationType {
            get {
                return ResourceManager.GetString("Word_EnumerationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   February に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_February {
            get {
                return ResourceManager.GetString("Word_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_First {
            get {
                return ResourceManager.GetString("Word_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_FolderName {
            get {
                return ResourceManager.GetString("Word_FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fourth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Fourth {
            get {
                return ResourceManager.GetString("Word_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Free space に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_FreeSpace {
            get {
                return ResourceManager.GetString("Word_FreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Friday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Friday {
            get {
                return ResourceManager.GetString("Word_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Issue priorities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_IssuePriorities {
            get {
                return ResourceManager.GetString("Word_IssuePriorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   January に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_January {
            get {
                return ResourceManager.GetString("Word_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   July に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_July {
            get {
                return ResourceManager.GetString("Word_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   June に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_June {
            get {
                return ResourceManager.GetString("Word_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Language {
            get {
                return ResourceManager.GetString("Word_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Last {
            get {
                return ResourceManager.GetString("Word_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Licence に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Licence {
            get {
                return ResourceManager.GetString("Word_Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   March に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_March {
            get {
                return ResourceManager.GetString("Word_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   May に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_May {
            get {
                return ResourceManager.GetString("Word_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Monday {
            get {
                return ResourceManager.GetString("Word_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Months に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Months {
            get {
                return ResourceManager.GetString("Word_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Name {
            get {
                return ResourceManager.GetString("Word_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no attached files in where you selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_NotIncludeAttachedFile {
            get {
                return ResourceManager.GetString("Word_NotIncludeAttachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no database in where you selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_NotIncludeDatabase {
            get {
                return ResourceManager.GetString("Word_NotIncludeDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no plugins in where you selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_NotIncludePlugin {
            get {
                return ResourceManager.GetString("Word_NotIncludePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no themes in where you selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_NotIncludeTheme {
            get {
                return ResourceManager.GetString("Word_NotIncludeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   November に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_November {
            get {
                return ResourceManager.GetString("Word_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   October に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_October {
            get {
                return ResourceManager.GetString("Word_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   On に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_On {
            get {
                return ResourceManager.GetString("Word_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Options {
            get {
                return ResourceManager.GetString("Word_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plugins に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Plugin {
            get {
                return ResourceManager.GetString("Word_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ProgressState_Complete {
            get {
                return ResourceManager.GetString("Word_ProgressState_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ProgressState_Failed {
            get {
                return ResourceManager.GetString("Word_ProgressState_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Progress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ProgressState_InProgress {
            get {
                return ResourceManager.GetString("Word_ProgressState_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ProgressState_NotRequire {
            get {
                return ResourceManager.GetString("Word_ProgressState_NotRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ProgressState_NotStart {
            get {
                return ResourceManager.GetString("Word_ProgressState_NotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [All Projects] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ProjectAll {
            get {
                return ResourceManager.GetString("Word_ProjectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recur every に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_RecurEvery {
            get {
                return ResourceManager.GetString("Word_RecurEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   days に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_RecurEveryDays {
            get {
                return ResourceManager.GetString("Word_RecurEveryDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   weeks on に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_RecurEveryWeeks {
            get {
                return ResourceManager.GetString("Word_RecurEveryWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saturday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Saturday {
            get {
                return ResourceManager.GetString("Word_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Save {
            get {
                return ResourceManager.GetString("Word_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Second に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Second {
            get {
                return ResourceManager.GetString("Word_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder you want to restore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_SelectSourceDirectoryTitle {
            get {
                return ResourceManager.GetString("Word_SelectSourceDirectoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select where you want to save your backup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_SelectTargetDirectoryTitle {
            get {
                return ResourceManager.GetString("Word_SelectTargetDirectoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   September に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_September {
            get {
                return ResourceManager.GetString("Word_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ServiceAutomatic {
            get {
                return ResourceManager.GetString("Word_ServiceAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic (Delayed Start) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ServiceDelayedStart {
            get {
                return ResourceManager.GetString("Word_ServiceDelayedStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ServiceDisabled {
            get {
                return ResourceManager.GetString("Word_ServiceDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ServiceManual {
            get {
                return ResourceManager.GetString("Word_ServiceManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ServiceStartupType {
            get {
                return ResourceManager.GetString("Word_ServiceStartupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Sort {
            get {
                return ResourceManager.GetString("Word_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Source {
            get {
                return ResourceManager.GetString("Word_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Start {
            get {
                return ResourceManager.GetString("Word_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Backup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_StartBackup {
            get {
                return ResourceManager.GetString("Word_StartBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Restore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_StartRestore {
            get {
                return ResourceManager.GetString("Word_StartRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Stop {
            get {
                return ResourceManager.GetString("Word_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sunday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Sunday {
            get {
                return ResourceManager.GetString("Word_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_TargetProject {
            get {
                return ResourceManager.GetString("Word_TargetProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_TaskDescription {
            get {
                return ResourceManager.GetString("Word_TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_TaskName {
            get {
                return ResourceManager.GetString("Word_TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I would like to gratefully thank the following libraries and products at large for acknowledging. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Thanks {
            get {
                return ResourceManager.GetString("Word_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Themes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Theme {
            get {
                return ResourceManager.GetString("Word_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Third に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Third {
            get {
                return ResourceManager.GetString("Word_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thursday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Thursday {
            get {
                return ResourceManager.GetString("Word_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trigger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Trigger {
            get {
                return ResourceManager.GetString("Word_Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daily に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_TriggerDaily {
            get {
                return ResourceManager.GetString("Word_TriggerDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monthly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_TriggerMonthly {
            get {
                return ResourceManager.GetString("Word_TriggerMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_TriggerOneTime {
            get {
                return ResourceManager.GetString("Word_TriggerOneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weekly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_TriggerWeekly {
            get {
                return ResourceManager.GetString("Word_TriggerWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tuesday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Tuesday {
            get {
                return ResourceManager.GetString("Word_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Unknown {
            get {
                return ResourceManager.GetString("Word_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unkown space (%) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_UnknownSpace {
            get {
                return ResourceManager.GetString("Word_UnknownSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Url に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Url {
            get {
                return ResourceManager.GetString("Word_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Used space (MB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_UsedSpace {
            get {
                return ResourceManager.GetString("Word_UsedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_VersionInfo {
            get {
                return ResourceManager.GetString("Word_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wednesday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Wednesday {
            get {
                return ResourceManager.GetString("Word_Wednesday", resourceCulture);
            }
        }
    }
}
