//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedArmory.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedArmory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   dd/MM/yyyy HH:mm:ss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Format_BackupDate {
            get {
                return ResourceManager.GetString("Format_BackupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to {0} service に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Format_FailedDoService {
            get {
                return ResourceManager.GetString("Format_FailedDoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start of {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Format_StartService {
            get {
                return ResourceManager.GetString("Format_StartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop of {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Format_StopService {
            get {
                return ResourceManager.GetString("Format_StopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Succeed to {0} service に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Format_SucceedDoService {
            get {
                return ResourceManager.GetString("Format_SucceedDoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Lang_English {
            get {
                return ResourceManager.GetString("Lang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Lang_Japanese {
            get {
                return ResourceManager.GetString("Lang_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup is cancelled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_BackupCancel {
            get {
                return ResourceManager.GetString("Msg_BackupCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup is complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_BackupComplete {
            get {
                return ResourceManager.GetString("Msg_BackupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_BackupFailed {
            get {
                return ResourceManager.GetString("Msg_BackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup is skipped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_BackupSkip {
            get {
                return ResourceManager.GetString("Msg_BackupSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitnami Redmine Stack is not present. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_BitnamiRedmineStackIsNotPresent {
            get {
                return ResourceManager.GetString("Msg_BitnamiRedmineStackIsNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete the selected history item? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_DeleteHistory {
            get {
                return ResourceManager.GetString("Msg_DeleteHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The output directory is not empty. Do you want to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_DirectoryIsNotEmpty {
            get {
                return ResourceManager.GetString("Msg_DirectoryIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore is cancelled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_RestoreCancel {
            get {
                return ResourceManager.GetString("Msg_RestoreCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore is complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_RestoreComplete {
            get {
                return ResourceManager.GetString("Msg_RestoreComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_RestoreFailed {
            get {
                return ResourceManager.GetString("Msg_RestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore is skipped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_RestoreSkip {
            get {
                return ResourceManager.GetString("Msg_RestoreSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %LONGDATE% : yyyyMMdd hhmmss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_FolderNameLongDate {
            get {
                return ResourceManager.GetString("Tooltip_FolderNameLongDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %SHORTDATE% : yyyyMMdd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_FolderNameShortDate {
            get {
                return ResourceManager.GetString("Tooltip_FolderNameShortDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %VERSION% : Version of Redmine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_FolderNameVersion {
            get {
                return ResourceManager.GetString("Tooltip_FolderNameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select where you want to save your backup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_SelectBackupFolder {
            get {
                return ResourceManager.GetString("Tooltip_SelectBackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder you want to restore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_SelectRestoreFolder {
            get {
                return ResourceManager.GetString("Tooltip_SelectRestoreFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Backup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_StartBackup {
            get {
                return ResourceManager.GetString("Tooltip_StartBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Restore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_StartRestore {
            get {
                return ResourceManager.GetString("Tooltip_StartRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About this application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_AboutThisApplication {
            get {
                return ResourceManager.GetString("Word_AboutThisApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Acknowledgements に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Acknowledgements {
            get {
                return ResourceManager.GetString("Word_Acknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attached Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_AttachedFile {
            get {
                return ResourceManager.GetString("Word_AttachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Author {
            get {
                return ResourceManager.GetString("Word_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Free space (MB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_AvailableSpace {
            get {
                return ResourceManager.GetString("Word_AvailableSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Database {
            get {
                return ResourceManager.GetString("Word_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Description {
            get {
                return ResourceManager.GetString("Word_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Destination {
            get {
                return ResourceManager.GetString("Word_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_FolderName {
            get {
                return ResourceManager.GetString("Word_FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Free space に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_FreeSpace {
            get {
                return ResourceManager.GetString("Word_FreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Language {
            get {
                return ResourceManager.GetString("Word_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Licence に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Licence {
            get {
                return ResourceManager.GetString("Word_Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no attached files in where you selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_NotIncludeAttachedFile {
            get {
                return ResourceManager.GetString("Word_NotIncludeAttachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no database in where you selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_NotIncludeDatabase {
            get {
                return ResourceManager.GetString("Word_NotIncludeDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no plugins in where you selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_NotIncludePlugin {
            get {
                return ResourceManager.GetString("Word_NotIncludePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no themes in where you selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_NotIncludeTheme {
            get {
                return ResourceManager.GetString("Word_NotIncludeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Options {
            get {
                return ResourceManager.GetString("Word_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plugins に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Plugin {
            get {
                return ResourceManager.GetString("Word_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ProgressState_Complete {
            get {
                return ResourceManager.GetString("Word_ProgressState_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ProgressState_Failed {
            get {
                return ResourceManager.GetString("Word_ProgressState_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Progress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ProgressState_InProgress {
            get {
                return ResourceManager.GetString("Word_ProgressState_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ProgressState_NotRequire {
            get {
                return ResourceManager.GetString("Word_ProgressState_NotRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ProgressState_NotStart {
            get {
                return ResourceManager.GetString("Word_ProgressState_NotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder you want to restore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_SelectSourceDirectoryTitle {
            get {
                return ResourceManager.GetString("Word_SelectSourceDirectoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select where you want to save your backup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_SelectTargetDirectoryTitle {
            get {
                return ResourceManager.GetString("Word_SelectTargetDirectoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ServiceAutomatic {
            get {
                return ResourceManager.GetString("Word_ServiceAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic (Delayed Start) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ServiceDelayedStart {
            get {
                return ResourceManager.GetString("Word_ServiceDelayedStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ServiceDisabled {
            get {
                return ResourceManager.GetString("Word_ServiceDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ServiceManual {
            get {
                return ResourceManager.GetString("Word_ServiceManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_ServiceStartupType {
            get {
                return ResourceManager.GetString("Word_ServiceStartupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Source {
            get {
                return ResourceManager.GetString("Word_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Start {
            get {
                return ResourceManager.GetString("Word_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Backup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_StartBackup {
            get {
                return ResourceManager.GetString("Word_StartBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Restore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_StartRestore {
            get {
                return ResourceManager.GetString("Word_StartRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Stop {
            get {
                return ResourceManager.GetString("Word_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I would like to gratefully thank the following libraries and products at large for acknowledging. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Thanks {
            get {
                return ResourceManager.GetString("Word_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Themes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Theme {
            get {
                return ResourceManager.GetString("Word_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Unknown {
            get {
                return ResourceManager.GetString("Word_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unkown space (%) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_UnknownSpace {
            get {
                return ResourceManager.GetString("Word_UnknownSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Url に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_Url {
            get {
                return ResourceManager.GetString("Word_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Used space (MB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_UsedSpace {
            get {
                return ResourceManager.GetString("Word_UsedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Word_VersionInfo {
            get {
                return ResourceManager.GetString("Word_VersionInfo", resourceCulture);
            }
        }
    }
}
